server:
  port: 8080

spring:
  application:
    name: cine conecta

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://cineconectav2.postgres.database.azure.com:5432/cineconecta}
    username: ${SPRING_DATASOURCE_USERNAME:cine_conecta_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:cubito1234!}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 60MB

  tmdb:
    api-key: 33d6f9d20e39e104025fe947df34c197 # Clave V3 de TMDb de KarolV
    base-url: https://api.themoviedb.org/3
    image-base-url: https://image.tmdb.org/t/p/
    poster-size: w342 # w92, w154, w185, w342, w500, w780, original
    #w342 es el mas cercano al tamano en front, pero si se ve pixelado cambiar a w500

  # application.properties
  cpp:
    cpp.api.base-url= http://localhost:5000

#azure:
#  storage:
#    connection_string: ${AZURE_STORAGE_CONNECTION}
#    container_name: ${AZURE_STORAGE_NAME}